version: '3.7'

services:

  db:
    image: timescale/timescaledb:latest-pg11
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      # use of subdir recommended when working with filesystem mountpoints
      POSTGRES_DB: ${PGDATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data/pgdata
        volume:
          nocopy: true
      - type: bind
        source: ./scripts
        target: /opt/sql/scripts/
    deploy:
      restart_policy:
          condition: none

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  pgdata:
